"""
train_model.py
─────────────────────────────────────────────────────────────────────────────
Trains a Scikit-Learn Random Forest Classifier on the synthetic HVAC chiller
dataset generated by simulate_pf_curve_data.py.

Features (9)
────────────
  suction_temp, discharge_temp, suction_press, discharge_press,
  vibration_rms, power_draw, oil_pressure, runtime_hours, ambient_temp

Target
──────
  failure_imminent  (binary: 0 = nominal, 1 = failure window)

Output
──────
  Trained model artifact saved as `model.pkl` in the backend/ directory,
  ready for the FastAPI lifespan loader to pick up on next server restart.

Usage
─────
  python ml_pipeline/train_model.py
"""

import os
import sys
from pathlib import Path

import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix,
    f1_score,
    roc_auc_score,
)
import joblib


# ── Paths ─────────────────────────────────────────────────────────────────────

SCRIPT_DIR: Path = Path(__file__).resolve().parent
PROJECT_ROOT: Path = SCRIPT_DIR.parent
DATASET_PATH: Path = SCRIPT_DIR / "hvac_sensor_data.csv"
MODEL_OUTPUT_PATH: Path = PROJECT_ROOT / "backend" / "model.pkl"

# ── Feature / target configuration ────────────────────────────────────────────

FEATURE_COLUMNS: list[str] = [
    "suction_temp",
    "discharge_temp",
    "suction_press",
    "discharge_press",
    "vibration_rms",
    "power_draw",
    "oil_pressure",
    "runtime_hours",
    "ambient_temp",
]

TARGET_COLUMN: str = "failure_imminent"

# ── Hyperparameters ───────────────────────────────────────────────────────────

RANDOM_STATE: int = 42
TEST_SIZE: float = 0.20
N_ESTIMATORS: int = 200
MAX_DEPTH: int = 12
MIN_SAMPLES_SPLIT: int = 5
MIN_SAMPLES_LEAF: int = 2


# ══════════════════════════════════════════════════════════════════════════════
#  TRAINING PIPELINE
# ══════════════════════════════════════════════════════════════════════════════

def load_dataset(path: Path) -> pd.DataFrame:
    """Load and validate the CSV dataset."""
    if not path.exists():
        print(f"❌  Dataset not found at {path}")
        sys.exit(1)

    df: pd.DataFrame = pd.read_csv(path)
    print(f"📊  Loaded dataset: {len(df)} rows × {len(df.columns)} columns")
    print(f"    Features: {FEATURE_COLUMNS}")
    print(f"    Target  : {TARGET_COLUMN}")

    # Validate expected columns
    missing = set(FEATURE_COLUMNS + [TARGET_COLUMN]) - set(df.columns)
    if missing:
        print(f"❌  Missing columns in dataset: {missing}")
        sys.exit(1)

    return df


def prepare_data(df: pd.DataFrame) -> tuple:
    """Split features and target, then create train/test sets."""
    X = df[FEATURE_COLUMNS].values
    y = df[TARGET_COLUMN].values

    print(f"\n📈  Target distribution:")
    print(f"    Class 0 (nominal) : {(y == 0).sum()} ({(y == 0).mean():.1%})")
    print(f"    Class 1 (failure) : {(y == 1).sum()} ({(y == 1).mean():.1%})")

    X_train, X_test, y_train, y_test = train_test_split(
        X, y,
        test_size=TEST_SIZE,
        random_state=RANDOM_STATE,
        stratify=y,
    )

    print(f"\n🔀  Train/Test split ({1 - TEST_SIZE:.0%}/{TEST_SIZE:.0%}):")
    print(f"    Train: {len(X_train)} samples")
    print(f"    Test : {len(X_test)} samples")

    return X_train, X_test, y_train, y_test


def train_model(X_train, y_train) -> RandomForestClassifier:
    """Train the Random Forest Classifier."""
    print(f"\n🌲  Training RandomForestClassifier...")
    print(f"    n_estimators    : {N_ESTIMATORS}")
    print(f"    max_depth       : {MAX_DEPTH}")
    print(f"    min_samples_split: {MIN_SAMPLES_SPLIT}")
    print(f"    min_samples_leaf : {MIN_SAMPLES_LEAF}")
    print(f"    random_state    : {RANDOM_STATE}")

    model = RandomForestClassifier(
        n_estimators=N_ESTIMATORS,
        max_depth=MAX_DEPTH,
        min_samples_split=MIN_SAMPLES_SPLIT,
        min_samples_leaf=MIN_SAMPLES_LEAF,
        random_state=RANDOM_STATE,
        class_weight="balanced",
        n_jobs=-1,
    )

    model.fit(X_train, y_train)
    print("✅  Model training complete.")

    return model


def evaluate_model(model: RandomForestClassifier, X_test, y_test) -> None:
    """Evaluate the trained model and print metrics."""
    y_pred = model.predict(X_test)
    y_proba = model.predict_proba(X_test)[:, 1]

    accuracy = accuracy_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)
    auc = roc_auc_score(y_test, y_proba)

    print(f"\n{'═' * 60}")
    print(f"  MODEL EVALUATION REPORT")
    print(f"{'═' * 60}")
    print(f"  Accuracy  : {accuracy:.4f}  ({accuracy:.1%})")
    print(f"  F1 Score  : {f1:.4f}")
    print(f"  ROC AUC   : {auc:.4f}")
    print(f"{'─' * 60}")
    print(f"\n  Classification Report:")
    print(classification_report(y_test, y_pred, target_names=["Nominal", "Failure"]))

    print(f"  Confusion Matrix:")
    cm = confusion_matrix(y_test, y_pred)
    print(f"    TN={cm[0][0]}  FP={cm[0][1]}")
    print(f"    FN={cm[1][0]}  TP={cm[1][1]}")

    # Feature importance
    importances = model.feature_importances_
    sorted_idx = np.argsort(importances)[::-1]
    print(f"\n{'─' * 60}")
    print(f"  Feature Importance Ranking:")
    for i, idx in enumerate(sorted_idx):
        bar = "█" * int(importances[idx] * 50)
        print(f"    {i + 1}. {FEATURE_COLUMNS[idx]:<20s} {importances[idx]:.4f}  {bar}")
    print(f"{'═' * 60}\n")


def export_model(model: RandomForestClassifier, path: Path) -> None:
    """Save the trained model as a joblib artifact."""
    path.parent.mkdir(parents=True, exist_ok=True)
    joblib.dump(model, path)
    file_size_kb = path.stat().st_size / 1024
    print(f"💾  Model saved → {path}  ({file_size_kb:.1f} KB)")


# ══════════════════════════════════════════════════════════════════════════════
#  ENTRY POINT
# ══════════════════════════════════════════════════════════════════════════════

def main() -> None:
    """Full pipeline: load → split → train → evaluate → export."""
    print("🔧  HVAC Predictive Maintenance — ML Training Pipeline")
    print("=" * 60)

    # 1. Load dataset
    df = load_dataset(DATASET_PATH)

    # 2. Prepare train/test data
    X_train, X_test, y_train, y_test = prepare_data(df)

    # 3. Train model
    model = train_model(X_train, y_train)

    # 4. Evaluate
    evaluate_model(model, X_test, y_test)

    # 5. Export to backend/
    export_model(model, MODEL_OUTPUT_PATH)

    print("🚀  Training pipeline complete. Restart the FastAPI server to load the new model.")


if __name__ == "__main__":
    main()
